package com.mecscable.billing.dto.response;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.List;

public record CustomerResponse(
        Long customerId,
        String firstName,
        String lastName,
        String doorNumber,
        Long streetId,
        String streetName,
        Long areaId,
        String areaName,
        Long cityId,
        String cityName,
        Long companyId,
        String companyName,
        String phone,
        String email,
        String upiId,
        String stbId,
        String status,
        String subscriptionStatus,
        BigDecimal lastPaymentAmount,
        LocalDate lastPaymentDate,
        BigDecimal currentPaymentAmount,
        LocalDate currentPaymentDate,
        LocalDate currentPaymentDueDate,
        LocalDate currentSubscriptionStart,
        LocalDate currentSubscriptionEnd,
        LocalDate gracePeriodDeadline,
        OffsetDateTime accountCreatedAt,
        String futureSubscriptionStatus,
        List<PackSummary> currentPacks,
        Long currentSubscriptionId,
        LocalDate currentSubscriptionDeactivationDate,
        Long futureSubscriptionId,
        LocalDate futureSubscriptionDeactivationDate
) {}
